### ISSUE TITLE
Release Beta v0.500.0

### ISSUE THREAD

**Issue by AdamHirst** [Orkanna/Orkanna#5]
Beta release v0.500.0 minimum requirements:
- [ ] Fix remote images loading on incorrect thread
- [ ] #2 Fix filter menu interactions
- [ ] #3 Fix starring interactions
- [ ] Fix opening hours displayed on non-applicable profiles
- [ ] #4 OSM integration (dependent on reliability testing)
- [ ] Implement iOS map renderer in preparation for iOS release
